### ISSUE TITLE
Please update abseil version dependency

### ISSUE THREAD

**Issue by vovaani** [rules-proto-grpc/rules_proto_grpc#191]
### Issue Description

Current version of abseil that rules_proto_grpc depends on fails to build with xcode 13.3, with the following error - 

```
external/com_google_absl/absl/functional/function_ref.h:124:16: error: definition of implicit copy constructor for 'FunctionRef<void (absl::string_view)>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
```

This was fixed at a newer version of abseil.

### rules_proto_grpc Version

4.1.1

### Bazel Version

4.2.2

### OS

MacOS 12.3.1

**Comment by maxbennedich** [comment]
Just a note that we'd love to see a fix for this, since for some time now our repo does not build with newer versions of Xcode, which is causing quite a bit of developer frustration. If there's any workaround while we're waiting for 4.2.0 that would be awesome.

We've tried adding `--host_copt=-Wno-error=deprecated-copy` on our side, but haven't gotten it to work since `-Wextra -Werror` is being added afterwards somewhere, which overrides our setting.
