### PR TITLE
Next Release 4.2.0

### LINKED ISSUE #172: Fix BuildKite
### Description

Bazel BuildKite recently added a cap on number of tasks, which breaks CI. Need to aggregate all tests under a small number of tasks. How to do this with the test and example workspaces is TBD.

### LINKED ISSUE #175: Is it possible to expose filter_files rule and proto_compile_attrs?
### Description

We are writing our own layer on top of this project (which we love btw!) and have defined our own macro instead of using `objc_proto_library`.

However, in our own macro we want to use some of the rules and variables used by `objc_proto_library` such as `filter_files` and `proto_compile_attrs`.

We have to do:
```
load("@rules_proto_grpc//internal:compile.bzl", "proto_compile_attrs")
load("@rules_proto_grpc//internal:filter_files.bzl", "filter_files")
```

which works fine but feels weird to import internal only definitions. We could also copy paste them but figured its worthwhile to "expose" them anyways.

Thanks for the project!

### LINKED ISSUE #179: Please update gRPC to 1.43.0 or greater
### Description

Thanks for considering updating gRPC to version 1.43.0 or greater.

A few rationales why:
- [gRPC Core 1.43.0](https://github.com/grpc/grpc/releases/tag/v1.43.0) fixes out-of-order delivery of `XdsClient` watcher notifications,
- [gRPC Java 1.43.0](https://github.com/grpc/grpc-java/releases/tag/v1.43.0) fixes a `NullPointerException` with sensus as well as the way `XdsServer` handles some configurations,
- [gRPC Java 1.43.**1**](https://github.com/grpc/grpc-java/releases/tag/v1.43.1) fixes a `StatusRuntimeException: INTERNAL: Panic! This is a bug!` when calling `ManagedChannel.enterIdle`,
- [Apache Beam 2.36.0](https://github.com/apache/beam/blob/master/CHANGES.md#2360---2022-02-07) depends on gRPC Java 1.43.2, which leads us to manually resolve (strict) dependency conflicts (side note: Apache Beam 2.37.0 will add Java 17 support for Dataflow, so keeping up with is important to us).

### LINKED ISSUE #181: Cannot find libstdc++-6.dll with MinGW
### Issue Description

When `protoc` is compiled with MinGW, it has a dependency on `libstdc++-6.dll` which is found (typically) in `C:\msys64\mingw64\bin`.

The only way an executable can find this DLL is by having `C:\msys64\mingw64\bin` in it's `PATH`, but `rules_proto_grpc` runs `protoc` without passing `use_default_shell_env = True` which causes it to run with only the workspace root in the `PATH`, preventing `libstdc++-6.dll` from being found.

Issue can be reprocuced by running `bazel build --compiler=mingw-gcc //...` in the `example/c/c_proto_compile` directory on Windows, with MinGW installed.

### Log Output

```plain text
INFO: Invocation ID: 9cab3575-b92f-442b-afd9-374be79aecb9
DEBUG: Rule 'com_google_absl' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "316cb2947e0a39a9359071991c2632418a466c78f3d27a7efe8d30dd384a0d06"
DEBUG: Repository com_google_absl instantiated at:
  C:/projects/rules_proto_grpc/example/c/c_proto_compile/WORKSPACE:24:9: in <toplevel>
  C:/users/blah/_bazel_blah/ir7hhvo4/external/upb/bazel/workspace_deps.bzl:5:10: in upb_deps
  C:/users/blah/_bazel_blah/ir7hhvo4/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
  C:/users/blah/_bazel_blah/ir7hhvo4/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
INFO: Analyzed 3 targets (2 packages loaded, 4 targets configured).
INFO: Found 3 targets...
ERROR: C:/projects/rules_proto_grpc/example/c/c_proto_compile/BUILD.bazel:13:16: Compiling protoc outputs for upb_plugin plugin on target //:thing_c_proto failed: (Exit 127): bash.exe failed: error executing command C:\msys64\usr\bin\bash.exe -c mkdir -p 'bazel-out/x64_windows-fastbuild/bin/_rpg_premerge_thing_c_proto' && bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe $@  ... (remaining 4 arguments skipped)
C:/users/blah/_bazel_blah/ir7hhvo4/execroot/__main__/bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory
ERROR: C:/projects/rules_proto_grpc/example/c/c_proto_compile/BUILD.bazel:3:16: Compiling protoc outputs for upb_plugin plugin on target //:person_c_proto failed: (Exit 127): bash.exe failed: error executing command C:\msys64\usr\bin\bash.exe -c mkdir -p 'bazel-out/x64_windows-fastbuild/bin/_rpg_premerge_person_c_proto' && bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe $@  ... (remaining 4 arguments skipped)
C:/users/blah/_bazel_blah/ir7hhvo4/execroot/__main__/bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory
ERROR: C:/projects/rules_proto_grpc/example/c/c_proto_compile/BUILD.bazel:8:16: Compiling protoc outputs for upb_plugin plugin on target //:place_c_proto failed: (Exit 127): bash.exe failed: error executing command C:\msys64\usr\bin\bash.exe -c mkdir -p 'bazel-out/x64_windows-fastbuild/bin/_rpg_premerge_place_c_proto' && bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe $@  ... (remaining 4 arguments skipped)
C:/users/blah/_bazel_blah/ir7hhvo4/execroot/__main__/bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/external/com_google_protobuf/protoc.exe: error while loading shared libraries: libstdc++-6.dll: cannot open shared object file: No such file or directory
INFO: Elapsed time: 1.480s, Critical Path: 0.46s
INFO: 4 processes: 4 internal.
FAILED: Build did NOT complete successfully
```

### rules_proto_grpc Version

master

### Bazel Version

5.0.0

### OS

Windows 10

### Link to Demo Repo

https://github.com/rules-proto-grpc/rules_proto_grpc/tree/master/example/c/c_proto_compile

### WORKSPACE Content

_No response_

### BUILD Content

_No response_

### Proto Content

_No response_

### Any Other Content

_No response_

### LINKED ISSUE #189: Generate python code without requiring py_library imports
### Description

For a given proto file `first/second/mylib.proto`, I would like to generate `runfiles/workspace/first/second/mylib_pb2.py`, however

* `NO_PREFIX` produces `runfiles/workspace/first/second/first/second/mylib_pb2.py`
* `PREFIXED` produces `runfiles/workspace/first/second/mylib_py_proto_generated_py/first//second/mylib_pb2.py`

Both of these depend on py_library `imports` flag in order to set PYTHONPATH correctly at runtime.  This is done in the generated py_binary wrapper.

If I want to use this library without running a py_binary entrypoint, the PYTHONPATH would be difficult to predict.  An example of this would be a python module that is loaded using the cpython API instead of being run as a standalone executable.

I propose adding a non-default mode ex. `NO_PREFIX_FLAT` which writes the generated files to the output path without any prefixes.

### LINKED ISSUE #191: Please update abseil version dependency
### Issue Description

Current version of abseil that rules_proto_grpc depends on fails to build with xcode 13.3, with the following error - 

```
external/com_google_absl/absl/functional/function_ref.h:124:16: error: definition of implicit copy constructor for 'FunctionRef<void (absl::string_view)>' is deprecated because it has a user-declared copy assignment operator [-Werror,-Wdeprecated-copy]
```

This was fixed at a newer version of abseil.

### Log Output

_No response_

### rules_proto_grpc Version

4.1.1

### Bazel Version

4.2.2

### OS

MacOS 12.3.1

### Link to Demo Repo

_No response_

### WORKSPACE Content

_No response_

### BUILD Content

_No response_

### Proto Content

_No response_

### Any Other Content

_No response_

### LINKED ISSUE #192: M1 / arm64 support for buf
### Issue Description

Buf supports M1 / arm64 builds. rules_proto_grpc doesn't support this new architecture and the builds fail for those users. https://github.com/bufbuild/buf/releases/tag/v1.3.1

### Log Output

```plain text
ERROR: /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/rules_proto_grpc/buf/BUILD.bazel:14:13: configurable attribute "tool" in @rules_proto_grpc//buf:lint_plugin doesn't match this configuration. Would a default condition help?

Conditions checked:
 @bazel_tools//src/conditions:darwin_x86_64
 @bazel_tools//src/conditions:linux_x86_64

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @rules_proto_grpc//buf:lint_plugin has configuration identifier ce088d1. To inspect its configuration, run: bazel config ce088d1.

For more help, see https://docs.bazel.build/configurable-attributes.html#why-doesnt-my-select-choose-what-i-expect.

INFO: Repository remote_coverage_tools instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:3:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/8c069df52082beee3c95ca17836fb8e2/external/bazel_tools/tools/build_defs/repo/http.bzl:364:31: in <toplevel>
```

### rules_proto_grpc Version

4.1.1

### Bazel Version

5.0.0

### OS

MacOS M1

### Link to Demo Repo

_No response_

### WORKSPACE Content

_No response_

### BUILD Content

_No response_

### Proto Content

_No response_

### Any Other Content

_No response_

### LINKED ISSUE #200: Use Grpc.Net instead of Grpc.Core (csharp)
### Description

Grpc.Core is an old package that wraps C library, it's now in maintenance mode and will be deprecated in May 2023 (see https://grpc.io/blog/grpc-csharp-future/)

Consider migrating to Grpc.Net.* package(s) which is new native implementation by Microsoft.

Grpc.Net.* packages are backward compatible with Grpc.Core and it probably be enough to just replace
```
${TOOL} add --path "${OUTPUT_DIR}" --indent --bazelfile "${FILE_NAME}" Grpc "${GRPC_VERSION}"
```
with
```
${TOOL} add --path "${OUTPUT_DIR}" --indent --bazelfile "${FILE_NAME}" Grpc.Net.Common "${GRPC_VERSION}"
```
at https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/csharp/nuget/regenerate_packages.sh#L50, but I'm not sure, because I'm not fully understand what happens over there :)

### LINKED ISSUE #208: Buf rules woefully out of date
### Issue Description

Here, `v0.56.0` is reference for buf -- https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/repositories.bzl#L78

Latest release is `v1.6.0` https://github.com/bufbuild/buf/releases/

### Log Output

_No response_

### rules_proto_grpc Version

master latest (2e8be8e27cc82203794f14dbdcf37189b02ab722)

### Bazel Version

latest

### OS

darwin arm64

### Link to Demo Repo

_No response_

### WORKSPACE Content

_No response_

### BUILD Content

_No response_

### Proto Content

_No response_

### Any Other Content

_No response_

### LINKED ISSUE #212: JS rules don't work with latest protobuf (3.21.x) repo
### Description

For some unknown reason, Google removed JavaScript support from the core protocolbuffers repo: https://github.com/protocolbuffers/protobuf/pull/9874

This makes rules_proto_grpc unable to generate JavaScript protos. The correct new way to do things is to bring in https://github.com/protocolbuffers/protobuf-javascript and use it as a plugin to protoc.

The error I get currently with a rules_proto_grpc JS target is: "protoc-gen-js: program not found or is not executable"

Thanks for your work on this, Adam!

@alexeagle FYI

### PR DESCRIPTION
**Pull request by aaliddell**
- Closes #175 
- Merges #177 
- Closes #181/Merges #182
- Closes #192 
- Closes #200
- Closes #212
- Closes #208
- Closes #191 
- Closes #189
- Closes #179
- Closes #172

### CODE REVIEW

**Comment by dnkoutso** [comment]
Hi there! Any luck on pushing this release forward? thank you in advance!

**Comment by ashwin153** [comment]
Can this be merged? Builds are currently broken on Python 3.10, because gRPC 1.42.0 uses the following code to determine the Python include path.

https://github.com/grpc/grpc/blob/v1.42.0/third_party/py/python_configure.bzl#L239-L243

While this code works on Python 3.10 it also emits a deprecation warning to stderr, and, for better or for worse, gRPC's Bazel rules treat commands as failed if they emit anything to stderr.

https://github.com/grpc/grpc/blob/v1.42.0/third_party/py/python_configure.bzl#L61-L66

**Comment by aaliddell** [comment]
It can't be merged as-is, as C++, Python and Go are still broken with the lastest gRPC release in CI and I've had very limited time to debug what is happening. As a workaround to get you going, you can force upgrade gRPC by adding this to your WORKSPACE **before** you load `rules_proto_grpc`:

```starlark
http_archive(
    name = "com_github_grpc_grpc",
    sha256 = "8c05641b9f91cbc92f51cc4a5b3a226788d7a63f20af4ca7aaca50d92cc94a0d",
    strip_prefix = "grpc-1.44.0",
    urls = ["https://github.com/grpc/grpc/archive/v1.44.0.tar.gz"],
)

# rules_proto_grpc should be loaded after, so below here
```

Note that one of the more recent gRPC releases added some deps I think, so you may not be able to use this trick to get all the way to 1.45.0, but 1.44.0 works and is compatible with Python 3.10.

**Comment by ashwin153** [comment]
Looks like all the versions after 1.42.0 pull in new dependencies. I keep getting build errors no matter what version I try. Would it be possible to just release the gRPC version bump as a patch release and then release the rest of the changes once you're able to resolve the build issues?

**Comment by ashwin153** [comment]
Actually I got it to work by adding the following to my WORKSPACE.

```
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
```

**Comment by loeffel-io** [comment]
any update? :-)

**Comment by aaliddell** [comment]
> any update? :-)

For context on why this is being so slow, we have a major test campaign that has been devouring my time since March. This will continue for at least another month, so updates here will unfortunately continue to be sporadic whilst that's ongoing.

To couple with that, every package update I make seems to introduce another few puzzling breakages 😩 

As it stands, you can try using this branch in your WORKSPACE if you absolutely need the updates, but beware of the bugs... 🐛 🐜 🐞 🐝 🪰

**Comment by dnkoutso** [comment]
Been watching progress on this! Thank you for pushing it forward!!
