### ISSUE TITLE
Feature request `ts_proto_library` & `ts_grpc_library`

### ISSUE THREAD

**Issue by loudmouth** [rules-proto-grpc/rules_proto_grpc#47]
Hi there,

Thanks so much for carrying the torch and providing these much needed rules. I'm in the process of migrating away from the `stackb` rules currently, and struggling to create `ts_library` for both protobuf and gRPC (a colleague who no longer works with me wrote the custom rules on top of `stackb` to generate the necessary typescript code previously).

While I have taken a stab at it, bazel is unfortunately not my forte. I thought I'd open an issue here and see if there was any interest in supporting both a `ts_proto_library` rule and a `ts_grpc_library` rule here since there is already at `ts_grpc_compile`.

Is there community need for TS proto+gRPC bazel rules?

**Comment by aaliddell** [comment]
I’m sure there’d be interest, but I’m not particularly familiar with the language. I vaguely remember looking at this before and getting a bit stumped with how a ts_library should be created for bunch of files using the upstream rules. If you have pointers on that, it’d be helpful!

**Comment by qzmfranklin** [comment]
@loudmouth 

My had exactly the same demands as you do. We searched pretty extensively. Until recently, there is not enough work done for making the combo of bazel+ts+proto+grpc fully functional.

We explored qutie a few close possibilities including grpc-web, grpc/js, protobufjs (rules_nodejs uses this) etc.. Unfortunately, they suffer from issues one after another. For example, grpc-web produces a different set of interfaces and classes from the ones generated by protobufjs.

I also asked @alexeagle (probably major personnel involved in the bazel+ts endeavor) somewhere on the internet (I forgot the exact location) about the idea of rolling out our own bazel+ts+proto+grpc infrastructure. He indicated that rules_nodejs does not own that part.

From the information I have collected and researched, I have come to a slightly risky conclusion that it is wise to roll out our own bazel+ts+proto+grpc infrastructure. Note that this is still being internally developed at LogiOcean Inc.. But I do plan to open source it after it passes a few important testing milestones.

So far we have completed the work on writing our own `ts_proto_library` which solves a few pain points we've had with the `ts_proto_library` rule shipped with the `rules_nodejs` repo:

- A `protoc-gen-ts` plugin framework written in Go for extensibility.
- The protoc plugin generates pure TypeScript codes that seamlessly work with the latest `ts_library` rules from `rules_nodejs` in Browsers, nodejs, and Electron.
- Use the canonical `protoc` binary to parse `.proto` files instead of having a custom parser of `.proto` of any sort (protobufjs does that).
- Allows transitive dependencies between `.proto` files to be clearly and easily managed, together with the `module_name` attribute of the `ts_library` rule.
- Allows for easily depending on third party `.proto` files.
- [WIP] Allows for writing annotations such as `google.api.http` and validators, and optionally generate corresponding code for those annotations.
- [WIP] First-class support for grpc over HTTP/2.

We have almost completed all of the above. Work is still underway to replace existing usages of the `ts_proto_library` and complete the WIP items.

Hopefully, someday we can open source this tooling infrastructure and make people like you happy. We've not been very loud about this effort. But I'd like it to help more people once our work stabilizes a little more.

**Comment by loudmouth** [comment]
Hey @qzmfranklin thanks so much for your detailed writeup of the current state of your work. I also tried to take a stab at this and attempted so many things in the past days that my brain is totally frazzled. I originally wanted to follow the approach outlined in this repo, but was never able to get a `ts_grpc_compile` working. A `ts_proto_compile` rule turned out to not be too difficult using the approach however: 

```python
proto_plugin(
    name = "ts_plugin",
    outputs = [
        "{protopath}_pb.d.ts",
    ],
    protoc_plugin_name = "ts",
    tool = "@managed_npm_deps//ts-protoc-gen/bin:protoc-gen-ts",
    visibility = ["//visibility:public"],
)
```

Regarding `ts_grpc_compile`, I fizzled out with an error that seems to suggest that the `--grpc_out` command line argument is not valid regardless of my approach. This is strange as running the command directly without bazel works just fine and that argument is certainly necessary. The relevant plugin in this case comes from [grpc-tools](https://www.npmjs.com/package/grpc-tools):

```python
proto_plugin(
    name = "grpc",
    outputs = ["{protopath}_grpc_pb.d.ts"],
    tool = "@managed_npm_deps//grpc-tools/bin:grpc_tools_node_protoc_plugin",
    visibility = ["//visibility:public"],

)
```

I thought it may be helpful to share what I think are the relevant `npm` based protoc plugins for generating typescript declarations:

- [GitHub - stultuss/protoc-gen-grpc-ts: Protocol compiler plugin for generating grpc interfaces in TypeScript.](https://github.com/stultuss/protoc-gen-grpc-ts)
- [GitHub - agreatfool/grpc_tools_node_protoc_ts: Generate TypeScript d.ts definitions for generated js files from grpc_tools_node_protoc](https://github.com/agreatfool/grpc_tools_node_protoc_ts)
- [GitHub - thesayyn/protoc-gen-ts: Generate Typescript files from Proto files.](https://github.com/thesayyn/protoc-gen-ts) — pure typescript

The last one could be an interesting one to keep an eye on for the future as it does not generate just typescript declarations, but TypeScript source code, presumably making it easier to wrap the outputs in a `ts_library`. 

I have sunk a lot of time into this topic this week, and believe that I won't be able to sustain the effort in the coming weeks, but hopefully this info might serve useful for somebody else.

**Comment by qzmfranklin** [comment]
Some updates from last time:

- [WIP] Support generating stub code in pure ts for unary grpc call over http/2 for the client side and the server side. Expected to fully launch internally in two weeks' time.
- The grpc codes work only works for nodejs and electron for now. That is, grpc-web, which make grpc calls in browsers, is not supported.
- We will investigate the feasibility and benefit of supporting grpc-web. There could be a few use cases. But we'd have to evaluate how demanding they are.

A bit of an ad for ourselves. I looked through all the links you provided. They are great repos. But none of them is designed to meet all the challenges that we've considered and anticipated - see my previous comment, but here are a few highlights:
- Native Bazel support.
- Native support for grpc over http/2.
- Generate pure TypeScript 3.7 code with very high coding standard.
- Works across browsers, nodejs, and electron.
- Support grpc-transcoding and other annotations such as validators.
- Extensible plugin system.

Hope this gives some more faith to you.

**Comment by pierreis** [comment]
I had some success in generating types for both gRPC and Protobuf based on the excellent work from @loudmouth.

Essentially, here is the plugin definition that I used:

```
proto_plugin(
    name = "ts_plugin",
    outputs = ["{protopath}_pb.d.ts"],
    protoc_plugin_name = "ts",
    tool = "@npm//ts-protoc-gen/bin:protoc-gen-ts",
    visibility = ["//visibility:public"],
)

proto_plugin(
    name = "grpc_ts_plugin",
    options = [
        "service=grpc-node",
    ],
    outputs = [
        "{protopath}_pb.d.ts",
        "{protopath}_grpc_pb.d.ts",
    ],
    protoc_plugin_name = "ts",
    tool = "@npm//ts-protoc-gen/bin:protoc-gen-ts",
    visibility = ["//visibility:public"],
)
```

**Comment by pierreis** [comment]
I could also make it work with `@grpc/grpc-js`, generating both Protobuf + gRPC `.js` + `.d.ts` artifacts with the following plugin configuration:

```py
proto_plugin(
    name = "grpc_js_plugin",
    options = [
        "generate_package_definition",
    ],
    outputs = ["{protopath}_grpc_pb.js"],
    protoc_plugin_name = "grpc_js",
    tool = "@npm//grpc-tools/bin:grpc_tools_node_protoc_plugin",
    visibility = ["//visibility:public"],
)

proto_plugin(
    name = "ts_plugin",
    outputs = ["{protopath}_pb.d.ts"],
    protoc_plugin_name = "ts",
    tool = "@npm//ts-protoc-gen/bin:protoc-gen-ts",
    visibility = ["//visibility:public"],
)

proto_plugin(
    name = "grpc_ts_plugin",
    options = [
        "generate_package_definition",
    ],
    outputs = [
        "{protopath}_pb.d.ts",
        "{protopath}_grpc_pb.d.ts",
    ],
    protoc_plugin_name = "ts",
    tool = "@npm//grpc_tools_node_protoc_ts/bin:protoc-gen-ts",
    visibility = ["//visibility:public"],
)
```

The aspect I am using is basically the standard one, with these plugins set:

```py
nodejs_grpc_compile_aspect = aspect(
    implementation = proto_compile_aspect_impl,
    provides = [ProtoLibraryAspectNodeInfo],
    attr_aspects = ["deps"],
    attrs = dict(
        proto_compile_aspect_attrs,
        _plugins = attr.label_list(
            doc = "List of protoc plugins to apply",
            providers = [ProtoPluginInfo],
            default = [
                Label("@rules_proto_grpc//nodejs:nodejs_plugin"),
                Label("//bazel/grpc:grpc_js_plugin"),
                Label("//bazel/grpc:grpc_ts_plugin"),
            ],
        ),
        _prefix = attr.string(
            doc = "String used to disambiguate aspects when generating outputs",
            default = "nodejs_grpc_compile_aspect",
        ),
    ),
    toolchains = [str(Label("@rules_proto_grpc//protobuf:toolchain_type"))],
)
```

**Comment by pierreis** [comment]
I have reached my next issue while working on a pull request to add typescript support, which is to feed the generated files to the `ts_library` rule.

I made some progress by adding a `DeclarationInfo` provider to add the metadata expected by `ts_library`, which allowed me to get a first success in compiling end-to-end `.proto` files in a typescript program with these rules.

But there is a catch.

`import * as pb from "./proto/address_pb"` doesn't work: cannot find module.
`import * as pb from "../proto/js_proto/service/address/proto/address_pb"` does work, but it is rather unsatisfying.

Would anyone have a tip on how to handle this case so that the files are mapped correctly?

**Comment by jrmurad** [comment]
@pierreis If you wouldn't mind sharing your code before the PR, I could take a look. From your snippet, I'm not sure how you got `@npm//` to work. In my previous attempt to deal with ts/grpc/bazel, I did something in tsconfig.json with `paths`.

**Comment by loudmouth** [comment]
I actually did get this working and i forgot to follow up here, apologies for that. I've zipped up the direcotry in my project for the rules, and this assumes that in the WORKSPACE file, there is a `yarn_install` rule invoked for the directory i just uploaded so that it's node_module deps will be installed by bazel. It generates `ts_library` types for both protobuf _and_ grpc and I consume them in other package/targets like so:


```
load("//tools/rules/ts_protobuf:ts_proto_library.bzl", "ts_proto_library")
load("//tools/rules/ts_protobuf:ts_grpc_library.bzl", "ts_grpc_library")

ts_proto_library(
    name = "address_ts",
    deps = [":address_proto"],
)

ts_grpc_library(
    name = "calendar_ts",
    deps = [":calendar_proto"],
)
```

[ts_grpc.zip](https://github.com/rules-proto-grpc/rules_proto_grpc/files/5061116/ts_grpc.zip)


Note that I've only confirmed this works with `rules_nodejs 1.0.2` and bazel version `2.1.1`

**Comment by jrmurad** [comment]
Thanks @loudmouth. I had a solution like that at first, calling `protoc` but I ran into an issue dealing with `import` in `.proto` files. I will check yours and see if that works there.

In the mean time, I did get rules_proto_grpc working but ran into an issue like @pierreis... I just don't like the output paths of generated files. I think I understand what it is doing to avoid conflicts but even if I have multiple services using the same shared generated code, I'd like to use a path like `import ... from 'dist/bin/example/common/greetings/hello_pb'` and the service from `dist/bin/example/greeter/greeter_grpc_pb`. The path is currently like `dist/bin/example/greeter/greeter_grpc/example/common/greetings/hello_grpc_pb`.

`bazel build //example/greeter:greeter_grpc`
[unity2.zip](https://github.com/rules-proto-grpc/rules_proto_grpc/files/5062599/unity2.zip)

**Comment by alexeagle** [comment]
I think https://github.com/rules-proto-grpc/rules_proto_grpc/pull/103 fixes this, in the sense that `DeclarationInfo` is provided by `nodejs_proto_library` so that it can be a dependency of ts_* rules

**Comment by loudmouth** [comment]
🎉 will have to check this out next week! thanks @alexeagle !

**Comment by aaliddell** [comment]
The changes mentioned above in #103 have landed in 3.0.0 :+1:
